name: syndisco-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - notebook
  - sphinx
  - myst-parser
  - nbsphinx
  - sphinx-autobuild
  - build
  - twine
  - pip
  - pip:
    - -r requirements.dev.txt